//==============================================================================
// Generated by: ac_create_build_config_header()
//         from: /usr/local/lib/acmake/templates/AcBuildConfiguration.h.in
//
//             DO NOT EDIT THIS FILE
//==============================================================================


#ifndef ACMAKE_BUILD_CONFIGURATION_INCLUDED
#define ACMAKE_BUILD_CONFIGURATION_INCLUDED

#ifdef CMAKE_INTDIR
#   define ACMAKE_BUILD_CONFIGURATION CMAKE_INTDIR
#else
#   define ACMAKE_BUILD_CONFIGURATION "Release"
#endif

namespace acmake {
    const char * const build_configuration = ACMAKE_BUILD_CONFIGURATION;
} // end of namespace acmake
#endif // ACMAKE_BUILD_CONFIGURATION_INCLUDED

