//==============================================================================
// Generated by: /usr/local/lib/acmake/cmake/AcPlatform.cmake
//         from: /usr/local/lib/acmake/templates/AcModuleName.h.in
//
//             DO NOT EDIT THIS FILE
//==============================================================================

#ifndef ACMAKE_MODULE_NAME_INCLUDED
#define ACMAKE_MODULE_NAME_INCLUDED

#include <string>

namespace acmake {

/** Returns the filename of a shared module for this platform given a cmake
 * target name
 */
inline
std::string
module_name(const char * target) {
    return std::string("lib") + target + ".dylib";
}

inline
std::string
module_extension() {
    return std::string(".dylib").substr(1);
}

} // end of namespace acmake

#endif // ACMAKE_MODULE_NAME_INCLUDED
