//==============================================================================
// Generated by: /usr/local/lib/acmake/tools/update_buildinfo_file.cmake
//         from: /usr/local/lib/acmake/templates/buildinfo.cpp.in
//
//             DO NOT EDIT THIS FILE
//==============================================================================

#include <asl/base/buildinfo.h>

/* #undef ACMAKE_HAVE_SVN_SCM */
#define ACMAKE_HAVE_GIT_SCM

#if defined(ACMAKE_HAVE_SVN_SCM)
#   define ACMAKE_SCM_DATA()                                \
            ACMAKE_SVN_REVISION( "",        \
                                 "" )
#elif defined(ACMAKE_HAVE_GIT_SCM)
#   define ACMAKE_SCM_DATA()                               \
            ACMAKE_GIT_REVISION("/Users/mirko/Development/Samples/y60vlc", \
                                "master",     \
                                "aa618f71de695d7a62f5869f95b3c5a400158500" )
#else
#   define ACMAKE_SCM_DATA() ACMAKE_NO_SCM_DATA()
#endif

ACMAKE_BUILDINFO("y60vlc", PLUGIN, ACMAKE_SCM_DATA(),
        y60vlc );
